/**
 * Custom exception indicating wrong graph specification.
 *
 * (This class is more specific than IllegalArgumentException and
 *  allows to catch only exceptions generated by inner workings of a game.)
 *
 * Author: Tomek
 */
public class WrongGraphSpecificationException extends IllegalArgumentException {

    public WrongGraphSpecificationException(String s) {
        super(s);
    }

    public WrongGraphSpecificationException(String message, Throwable cause) {
        super(message, cause);
    }

}
